# BUILD STAGE
FROM node:20.11.1-alpine as build-stage

## LOG SETTING
# RUN mkdir /logs
# RUN chmod 777 /logs

# LANGUAGE SETTING
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR:en
ENV LC_ALL ko_KR.UTF-8

# TIMEZONE SETTING
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm install

COPY . .
RUN npm run build-sit

# PRODUCTION STAGE
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
