export const {
  VITE_APP_TITLE,
  VITE_KEYCLOAK_ENABLED,
  VITE_KEYCLOAK_URL,
  VITE_KEYCLOAK_REALM,
  VITE_KEYCLOAK_CLIENT_ID,
  VITE_REFRESH_TOKEN_MS,
  VITE_CLUSTER_LIST,
  MODE,
  DEV: IsDevMode,
} = import.meta.env;
